// <auto-generated />
using HolidayManagement.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HolidayManagement.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HolidayManagement.Models.Office", b =>
                {
                    b.Property<string>("OfficeName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("OfficeName");

                    b.ToTable("Office");
                });

            modelBuilder.Entity("HolidayManagement.Models.Staff", b =>
                {
                    b.Property<int>("StaffID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Office")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfficesOfficeName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StaffStatusStatus")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StaffID");

                    b.HasIndex("OfficesOfficeName");

                    b.HasIndex("StaffStatusStatus");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("HolidayManagement.Models.StaffStatus", b =>
                {
                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Status");

                    b.ToTable("StaffStatus");
                });

            modelBuilder.Entity("HolidayManagement.Models.Staff", b =>
                {
                    b.HasOne("HolidayManagement.Models.Office", "Offices")
                        .WithMany()
                        .HasForeignKey("OfficesOfficeName");

                    b.HasOne("HolidayManagement.Models.StaffStatus", "StaffStatus")
                        .WithMany()
                        .HasForeignKey("StaffStatusStatus");
                });
#pragma warning restore 612, 618
        }
    }
}
